name: CI Autogen
on:
  workflow_dispatch:
  # schedule:
    # Saturday midnight
    # - cron: '0 0 * * 6'

jobs:
  autorun:
    name: automatic PR against libs
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install deps ⛓️
        run: |
          pacman -Sy --noconfirm go base-devel
    
      - name: Checkout repo ⤵️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: bumper
        
      - name: Build artifact
        run: |
          cd bumper
          make build

      - name: Checkout libs repo ⤵️
        uses: actions/checkout@v3
        with:
          repository: fededp/libs
          ref: 'master'
          path: libs
          
      - name: Generate new files
        run: |
          cd bumper
          ./build/bumper --repo-root $GITHUB_WORKSPACE/libs

      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
            source_folder: 'bumper/driver'
            destination_repo: 'fededp/libs'
            destination_folder: 'driver'
            destination_base_branch: 'master'
            destination_head_branch: 'update/autogenerate_syscalls'
            user_email: 'nierro92@gmail.com'
            user_name: 'fededp'
