name: CI Build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: build syscalls-bumper
    runs-on: ubuntu-latest
    steps:
      - name: Install deps ⛓️
        run: |
          sudo apt update
          sudo apt install golang build-essential
    
      - name: Checkout repo ⤵️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Build artifact
        run: |
          make build
